server.error.include-message=always
server.error.include-binding-errors=always

spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?user=postgres.dvrdjddboywudjmujclf&password=iamnotadata
spring.datasource.username=postgres.dvrdjddboywudjmujclf
spring.datasource.password=iamnotadata


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true